#if !defined(__DEMOAPP_H__)
#define __DEMOAPP_H__

#include "mmi_module.h"

typedef enum {
    MMIDEMOAPP_WIN_ID_START = (MMI_MODULE_DEMOAPP << 16),
    MMIDEMOAPP_WIN_ID_MAIN,
    MMIDEMOAPP_WIN_ID_END
} MMIDEMOAPP_WINDOW_ID_E;

typedef enum {
    MMIDEMOAPP_CTRL_ID_START = MMIDEMOAPP_WIN_ID_END,
    MMIDEMOAPP_CTRL_ID_RICHTEXT,
    MMIDEMOAPP_CTRL_ID_END
} MMIDEMOAPP_CONTROL_ID_E;
#endif
