print('我'.encode('utf-8'))
print('来'.encode('utf-8'))
print('我'.encode('gbk'))
print('来'.encode('gbk'))
print('{"text": "我来自Labview"}'.encode('utf-8'))
print(b'\xe6\x88\x91'.decode('utf-8'))
print('我'.encode('raw_unicode_escape'))
print('\u6211')
print('\u6211'.encode('utf-8'))
