// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Msg {
    #[prost(map = "string, int32", tag = "7")]
    pub g: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Msg2 {
    #[prost(message, repeated, tag = "7")]
    pub g: ::prost::alloc::vec::Vec<msg2::GEntry>,
}
/// Nested message and enum types in `Msg2`.
pub mod msg2 {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct GEntry {
        #[prost(string, tag = "1")]
        pub key: ::prost::alloc::string::String,
        #[prost(int32, tag = "2")]
        pub value: i32,
    }
}
