// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Msg {
    #[prost(int32, tag = "7")]
    pub f: i32,
    #[prost(oneof = "msg::A", tags = "4, 6")]
    pub a: ::core::option::Option<msg::A>,
}
/// Nested message and enum types in `Msg`.
pub mod msg {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum A {
        #[prost(string, tag = "4")]
        D(::prost::alloc::string::String),
        #[prost(int32, tag = "6")]
        E(i32),
    }
}
