[package]
name = "future"
edition = "2021"

[dependencies]
futures-sink = "0.3"
futures-core = "0.3"
futures-util = { version = "0.3", features = ["sink"] }
futures-executor = "0.3"
futures-channel = "0.3"
tower = { version = "0.5.2", features = ["util"] }
