[package]
name = "rust_crawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8.1"
reqwest = { version = "0.11.23", features = ["blocking"] }
select = "0.6.0"
