/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: addressbook.proto */

#ifndef PROTOBUF_C_addressbook_2eproto__INCLUDED
#define PROTOBUF_C_addressbook_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Person Person;
typedef struct _Person__PhoneNumber Person__PhoneNumber;
typedef struct _AddressBook AddressBook;


/* --- enums --- */

typedef enum _Person__PhoneType {
  PERSON__PHONE_TYPE__MOBILE = 0,
  PERSON__PHONE_TYPE__HOME = 1,
  PERSON__PHONE_TYPE__WORK = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PERSON__PHONE_TYPE)
} Person__PhoneType;

/* --- messages --- */

struct  _Person__PhoneNumber
{
  char *number;
  Person__PhoneType type;
};
struct  _Person
{
  char *name;
  int32_t id;
  char *email;
  size_t n_phones;
  Person__PhoneNumber **phones;
};
struct  _AddressBook
{
  size_t n_people;
  Person **people;
};
size_t person__get_packed_size
                     (const Person   *message);
size_t person__pack
                     (const Person   *message,
                      uint8_t             *out);
Person *
       person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   person__free_unpacked
                     (Person *message,
                      ProtobufCAllocator *allocator);
size_t address_book__get_packed_size
                     (const AddressBook   *message);
size_t address_book__pack
                     (const AddressBook   *message,
                      uint8_t             *out);
AddressBook *
       address_book__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   address_book__free_unpacked
                     (AddressBook *message,
                      ProtobufCAllocator *allocator);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor person__descriptor;
extern const ProtobufCMessageDescriptor person__phone_number__descriptor;
extern const ProtobufCEnumDescriptor    person__phone_type__descriptor;
extern const ProtobufCMessageDescriptor address_book__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_addressbook_2eproto__INCLUDED */
