/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: addressbook.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "addressbook.pb-c.h"
size_t person__get_packed_size
                     (const Person *message)
{
  return protobuf_c_message_get_packed_size ((const void*)message, &person__descriptor);
}
size_t person__pack
                     (const Person *message,
                      uint8_t       *out)
{
  return protobuf_c_message_pack ((const void*)message, &person__descriptor, out);
}
Person *
       person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Person *)
     protobuf_c_message_unpack (&person__descriptor,
                                allocator, len, data);
}
void   person__free_unpacked
                     (Person *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  protobuf_c_message_free_unpacked ((void*)message, &person__descriptor, allocator);
}
size_t address_book__get_packed_size
                     (const AddressBook *message)
{
  return protobuf_c_message_get_packed_size ((const void*)message, &address_book__descriptor);
}
size_t address_book__pack
                     (const AddressBook *message,
                      uint8_t       *out)
{
  return protobuf_c_message_pack ((const void*)message, &address_book__descriptor, out);
}
AddressBook *
       address_book__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AddressBook *)
     protobuf_c_message_unpack (&address_book__descriptor,
                                allocator, len, data);
}
void   address_book__free_unpacked
                     (AddressBook *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  protobuf_c_message_free_unpacked ((void*)message, &address_book__descriptor, allocator);
}
static const ProtobufCFieldDescriptor person__phone_number__field_descriptors[] =
{
  {
    1,
    0,   /* quantifier_offset */
    offsetof(Person__PhoneNumber, number),
    NULL,
    PROTOBUF_C_FIELD_FLAG_VTF(0) | PROTOBUF_C_LABEL_VTF(PROTOBUF_C_LABEL_NONE) | PROTOBUF_C_TYPE_VTF(PROTOBUF_C_TYPE_STRING)             /* flags */
  },
  {
    2,
    0,   /* quantifier_offset */
    offsetof(Person__PhoneNumber, type),
    NULL,
    PROTOBUF_C_FIELD_FLAG_VTF(0) | PROTOBUF_C_LABEL_VTF(PROTOBUF_C_LABEL_NONE) | PROTOBUF_C_TYPE_VTF(PROTOBUF_C_TYPE_ENUM)             /* flags */
  },
};
const ProtobufCMessageDescriptor person__phone_number__descriptor =
{
  sizeof(Person__PhoneNumber),
  sizeof(person__phone_number__field_descriptors) / sizeof(ProtobufCFieldDescriptor),
  person__phone_number__field_descriptors,
};
static const ProtobufCFieldDescriptor person__field_descriptors[] =
{
  {
    1,
    0,   /* quantifier_offset */
    offsetof(Person, name),
    NULL,
    PROTOBUF_C_FIELD_FLAG_VTF(0) | PROTOBUF_C_LABEL_VTF(PROTOBUF_C_LABEL_NONE) | PROTOBUF_C_TYPE_VTF(PROTOBUF_C_TYPE_STRING)             /* flags */
  },
  {
    2,
    0,   /* quantifier_offset */
    offsetof(Person, id),
    NULL,
    PROTOBUF_C_FIELD_FLAG_VTF(0) | PROTOBUF_C_LABEL_VTF(PROTOBUF_C_LABEL_NONE) | PROTOBUF_C_TYPE_VTF(PROTOBUF_C_TYPE_INT32)             /* flags */
  },
  {
    3,
    0,   /* quantifier_offset */
    offsetof(Person, email),
    NULL,
    PROTOBUF_C_FIELD_FLAG_VTF(0) | PROTOBUF_C_LABEL_VTF(PROTOBUF_C_LABEL_NONE) | PROTOBUF_C_TYPE_VTF(PROTOBUF_C_TYPE_STRING)             /* flags */
  },
  {
    4,
    offsetof(Person, n_phones),
    offsetof(Person, phones),
    &person__phone_number__descriptor,
    PROTOBUF_C_FIELD_FLAG_VTF(0) | PROTOBUF_C_LABEL_VTF(PROTOBUF_C_LABEL_REPEATED) | PROTOBUF_C_TYPE_VTF(PROTOBUF_C_TYPE_MESSAGE)             /* flags */
  },
};
const ProtobufCMessageDescriptor person__descriptor =
{
  sizeof(Person),
  sizeof(person__field_descriptors) / sizeof(ProtobufCFieldDescriptor),
  person__field_descriptors,
};
static const ProtobufCFieldDescriptor address_book__field_descriptors[] =
{
  {
    1,
    offsetof(AddressBook, n_people),
    offsetof(AddressBook, people),
    &person__descriptor,
    PROTOBUF_C_FIELD_FLAG_VTF(0) | PROTOBUF_C_LABEL_VTF(PROTOBUF_C_LABEL_REPEATED) | PROTOBUF_C_TYPE_VTF(PROTOBUF_C_TYPE_MESSAGE)             /* flags */
  },
};
const ProtobufCMessageDescriptor address_book__descriptor =
{
  sizeof(AddressBook),
  sizeof(address_book__field_descriptors) / sizeof(ProtobufCFieldDescriptor),
  address_book__field_descriptors,
};
