/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: empty.proto */

#ifndef PROTOBUF_C_empty_2eproto__INCLUDED
#define PROTOBUF_C_empty_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Empty Empty;


/* --- enums --- */


/* --- messages --- */

struct  _Empty
{
  char empty;
};
size_t empty__get_packed_size
                     (const Empty   *message);
size_t empty__pack
                     (const Empty   *message,
                      uint8_t             *out);
Empty *
       empty__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   empty__free_unpacked
                     (Empty *message,
                      ProtobufCAllocator *allocator);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor empty__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_empty_2eproto__INCLUDED */
