/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: empty.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "empty.pb-c.h"
size_t empty__get_packed_size
                     (const Empty *message)
{
  return protobuf_c_message_get_packed_size ((const void*)message, &empty__descriptor);
}
size_t empty__pack
                     (const Empty *message,
                      uint8_t       *out)
{
  return protobuf_c_message_pack ((const void*)message, &empty__descriptor, out);
}
Empty *
       empty__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Empty *)
     protobuf_c_message_unpack (&empty__descriptor,
                                allocator, len, data);
}
void   empty__free_unpacked
                     (Empty *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  protobuf_c_message_free_unpacked ((void*)message, &empty__descriptor, allocator);
}
#define empty__field_descriptors NULL
#define empty__field_indices_by_name NULL
#define empty__number_ranges NULL
const ProtobufCMessageDescriptor empty__descriptor =
{
  sizeof(Empty),
  sizeof(empty__field_descriptors) / sizeof(ProtobufCFieldDescriptor),
  empty__field_descriptors,
};
