/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test2.proto */

#ifndef PROTOBUF_C_test2_2eproto__INCLUDED
#define PROTOBUF_C_test2_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _A A;
typedef struct _B B;
typedef struct _C C;


/* --- enums --- */


/* --- messages --- */

struct  _A
{
  char *str;
};
struct  _B
{
  int32_t i;
};
struct  _C
{
  A *a;
  B *b;
};
size_t a__get_packed_size
                     (const A   *message);
size_t a__pack
                     (const A   *message,
                      uint8_t             *out);
A *
       a__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   a__free_unpacked
                     (A *message,
                      ProtobufCAllocator *allocator);
size_t b__get_packed_size
                     (const B   *message);
size_t b__pack
                     (const B   *message,
                      uint8_t             *out);
B *
       b__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   b__free_unpacked
                     (B *message,
                      ProtobufCAllocator *allocator);
size_t c__get_packed_size
                     (const C   *message);
size_t c__pack
                     (const C   *message,
                      uint8_t             *out);
C *
       c__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   c__free_unpacked
                     (C *message,
                      ProtobufCAllocator *allocator);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor a__descriptor;
extern const ProtobufCMessageDescriptor b__descriptor;
extern const ProtobufCMessageDescriptor c__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_test2_2eproto__INCLUDED */
