/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "addressbook.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Person, Person, AUTO)


PB_BIND(Person_PhoneNumber, Person_PhoneNumber, AUTO)


PB_BIND(AddressBook, AddressBook, AUTO)




