/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/addressbook.proto */

#ifndef PROTOBUF_C_proto_2faddressbook_2eproto__INCLUDED
#define PROTOBUF_C_proto_2faddressbook_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Person Person;
typedef struct _Person__PhoneNumber Person__PhoneNumber;
typedef struct _AddressBook AddressBook;


/* --- enums --- */

typedef enum _Person__PhoneType {
  PERSON__PHONE_TYPE__MOBILE = 0,
  PERSON__PHONE_TYPE__HOME = 1,
  PERSON__PHONE_TYPE__WORK = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PERSON__PHONE_TYPE)
} Person__PhoneType;

/* --- messages --- */

struct  _Person__PhoneNumber
{
  ProtobufCMessage base;
  char *number;
  Person__PhoneType type;
};
#define PERSON__PHONE_NUMBER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&person__phone_number__descriptor) \
    , (char *)protobuf_c_empty_string, PERSON__PHONE_TYPE__MOBILE }


struct  _Person
{
  ProtobufCMessage base;
  char *name;
  int32_t id;
  char *email;
  size_t n_phones;
  Person__PhoneNumber **phones;
};
#define PERSON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&person__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0,NULL }


struct  _AddressBook
{
  ProtobufCMessage base;
  size_t n_people;
  Person **people;
};
#define ADDRESS_BOOK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&address_book__descriptor) \
    , 0,NULL }


/* Person__PhoneNumber methods */
void   person__phone_number__init
                     (Person__PhoneNumber         *message);
/* Person methods */
void   person__init
                     (Person         *message);
size_t person__get_packed_size
                     (const Person   *message);
size_t person__pack
                     (const Person   *message,
                      uint8_t             *out);
size_t person__pack_to_buffer
                     (const Person   *message,
                      ProtobufCBuffer     *buffer);
Person *
       person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   person__free_unpacked
                     (Person *message,
                      ProtobufCAllocator *allocator);
/* AddressBook methods */
void   address_book__init
                     (AddressBook         *message);
size_t address_book__get_packed_size
                     (const AddressBook   *message);
size_t address_book__pack
                     (const AddressBook   *message,
                      uint8_t             *out);
size_t address_book__pack_to_buffer
                     (const AddressBook   *message,
                      ProtobufCBuffer     *buffer);
AddressBook *
       address_book__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   address_book__free_unpacked
                     (AddressBook *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Person__PhoneNumber_Closure)
                 (const Person__PhoneNumber *message,
                  void *closure_data);
typedef void (*Person_Closure)
                 (const Person *message,
                  void *closure_data);
typedef void (*AddressBook_Closure)
                 (const AddressBook *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor person__descriptor;
extern const ProtobufCMessageDescriptor person__phone_number__descriptor;
extern const ProtobufCEnumDescriptor    person__phone_type__descriptor;
extern const ProtobufCMessageDescriptor address_book__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2faddressbook_2eproto__INCLUDED */
