/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/addressbook.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "addressbook.pb-c.h"
void   person__phone_number__init
                     (Person__PhoneNumber         *message)
{
  static const Person__PhoneNumber init_value = PERSON__PHONE_NUMBER__INIT;
  *message = init_value;
}
void   person__init
                     (Person         *message)
{
  static const Person init_value = PERSON__INIT;
  *message = init_value;
}
size_t person__get_packed_size
                     (const Person *message)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t person__pack
                     (const Person *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t person__pack_to_buffer
                     (const Person *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &person__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Person *
       person__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Person *)
     protobuf_c_message_unpack (&person__descriptor,
                                allocator, len, data);
}
void   person__free_unpacked
                     (Person *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &person__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   address_book__init
                     (AddressBook         *message)
{
  static const AddressBook init_value = ADDRESS_BOOK__INIT;
  *message = init_value;
}
size_t address_book__get_packed_size
                     (const AddressBook *message)
{
  assert(message->base.descriptor == &address_book__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t address_book__pack
                     (const AddressBook *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &address_book__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t address_book__pack_to_buffer
                     (const AddressBook *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &address_book__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AddressBook *
       address_book__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AddressBook *)
     protobuf_c_message_unpack (&address_book__descriptor,
                                allocator, len, data);
}
void   address_book__free_unpacked
                     (AddressBook *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &address_book__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor person__phone_number__field_descriptors[2] =
{
  {
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Person__PhoneNumber, number),
    NULL,
    &protobuf_c_empty_string,
    0             /* flags */
  },
  {
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Person__PhoneNumber, type),
    &person__phone_type__descriptor,
    NULL,
    0             /* flags */
  },
};
const ProtobufCMessageDescriptor person__phone_number__descriptor =
{
  sizeof(Person__PhoneNumber),
  2,
  person__phone_number__field_descriptors,
  (ProtobufCMessageInit) person__phone_number__init
};
static const ProtobufCIntRange person__phone_type__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumDescriptor person__phone_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  1,
  person__phone_type__value_ranges
};
static const ProtobufCFieldDescriptor person__field_descriptors[4] =
{
  {
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Person, name),
    NULL,
    &protobuf_c_empty_string,
    0             /* flags */
  },
  {
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Person, id),
    NULL,
    NULL,
    0             /* flags */
  },
  {
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Person, email),
    NULL,
    &protobuf_c_empty_string,
    0             /* flags */
  },
  {
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Person, n_phones),
    offsetof(Person, phones),
    &person__phone_number__descriptor,
    NULL,
    0             /* flags */
  },
};
const ProtobufCMessageDescriptor person__descriptor =
{
  sizeof(Person),
  4,
  person__field_descriptors,
  (ProtobufCMessageInit) person__init
};
static const ProtobufCFieldDescriptor address_book__field_descriptors[1] =
{
  {
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(AddressBook, n_people),
    offsetof(AddressBook, people),
    &person__descriptor,
    NULL,
    0             /* flags */
  },
};
const ProtobufCMessageDescriptor address_book__descriptor =
{
  sizeof(AddressBook),
  1,
  address_book__field_descriptors,
  (ProtobufCMessageInit) address_book__init
};
