/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/test1.proto */

#ifndef PROTOBUF_C_proto_2ftest1_2eproto__INCLUDED
#define PROTOBUF_C_proto_2ftest1_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Test1 Test1;


/* --- enums --- */


/* --- messages --- */

struct  _Test1
{
  ProtobufCMessage base;
  char *f1;
  char *f2;
  char *f3;
  char *f4;
  char *f5;
  int32_t f6;
  int64_t f7;
  char *f8;
  char *f9;
};
#define TEST1__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&test1__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Test1 methods */
void   test1__init
                     (Test1         *message);
size_t test1__get_packed_size
                     (const Test1   *message);
size_t test1__pack
                     (const Test1   *message,
                      uint8_t             *out);
size_t test1__pack_to_buffer
                     (const Test1   *message,
                      ProtobufCBuffer     *buffer);
Test1 *
       test1__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   test1__free_unpacked
                     (Test1 *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Test1_Closure)
                 (const Test1 *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor test1__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2ftest1_2eproto__INCLUDED */
