/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_TEST1_PB_H_INCLUDED
#define PB_TEST1_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Test1 { 
    pb_callback_t f1; 
    pb_callback_t f2; 
    pb_callback_t f3; 
    pb_callback_t f4; 
    pb_callback_t f5; 
    int32_t f6; 
    int64_t f7; 
    pb_callback_t f8; 
    pb_callback_t f9; 
} Test1;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Test1_init_default                       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define Test1_init_zero                          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Test1_f1_tag                             1
#define Test1_f2_tag                             2
#define Test1_f3_tag                             3
#define Test1_f4_tag                             4
#define Test1_f5_tag                             5
#define Test1_f6_tag                             6
#define Test1_f7_tag                             7
#define Test1_f8_tag                             8
#define Test1_f9_tag                             9

/* Struct field encoding specification for nanopb */
#define Test1_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   f1,                1) \
X(a, CALLBACK, SINGULAR, STRING,   f2,                2) \
X(a, CALLBACK, SINGULAR, STRING,   f3,                3) \
X(a, CALLBACK, SINGULAR, STRING,   f4,                4) \
X(a, CALLBACK, SINGULAR, STRING,   f5,                5) \
X(a, STATIC,   SINGULAR, INT32,    f6,                6) \
X(a, STATIC,   SINGULAR, INT64,    f7,                7) \
X(a, CALLBACK, SINGULAR, STRING,   f8,                8) \
X(a, CALLBACK, SINGULAR, STRING,   f9,                9)
#define Test1_CALLBACK pb_default_field_callback
#define Test1_DEFAULT NULL

extern const pb_msgdesc_t Test1_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Test1_fields &Test1_msg

/* Maximum encoded size of messages (where known) */
/* Test1_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
