// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Repeated {
    #[prost(string, tag = "4")]
    pub d: ::prost::alloc::string::String,
    #[prost(int32, repeated, tag = "6")]
    pub e: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Packed {
    #[prost(string, tag = "4")]
    pub d: ::prost::alloc::string::String,
    #[prost(int32, repeated, packed = "false", tag = "6")]
    pub e: ::prost::alloc::vec::Vec<i32>,
}
