// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Msg {
    #[prost(int32, tag = "7")]
    pub a: i32,
    #[prost(sint32, tag = "8")]
    pub b: i32,
}
