// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SubMsg {
    #[prost(int32, tag = "1")]
    pub a: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Msg {
    #[prost(message, optional, tag = "3")]
    pub c: ::core::option::Option<SubMsg>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SubMsg2 {
    #[prost(int32, optional, tag = "1")]
    pub a: ::core::option::Option<i32>,
}
