[package]
name = "crypto"
edition = "2024"

[dependencies]
cbc = "0.2.0-pre.2"
aes = "0.9.0-pre.2"
inout = "0.2.0-rc.4"
hex-literal = "1"
ctr = "0.10.0-pre.2"

[features]
default = ["block-padding"]
block-padding = ["inout/block-padding"]
