SELECT * , COUNT(*) OVER (PARTITION BY cid, pid ORDER BY ctime ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
FROM channel_status

SELECT * , COUNT(*) OVER (PARTITION BY cid, pid ORDER BY ctime)
FROM channel_status

