CREATE TABLE [dbo].[tt2](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[type] [int] NOT NULL,
	[value] [int] NOT NULL,
 CONSTRAINT [PK_tt2] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SELECT
*
FROM (
SELECT
*,
ROW_NUMBER() OVER (PARTITION BY type ORDER BY value) AS rn
FROM tt2) AS t1
WHERE rn <= 2