/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test1.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "test1.pb-c.h"
size_t test1__get_packed_size
                     (const Test1 *message)
{
  return protobuf_c_message_get_packed_size ((const void*)message, &test1__descriptor);
}
size_t test1__pack
                     (const Test1 *message,
                      uint8_t       *out)
{
  return protobuf_c_message_pack ((const void*)message, &test1__descriptor, out);
}
Test1 *
       test1__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Test1 *)
     protobuf_c_message_unpack (&test1__descriptor,
                                allocator, len, data);
}
void   test1__free_unpacked
                     (Test1 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  protobuf_c_message_free_unpacked ((void*)message, &test1__descriptor, allocator);
}
static const ProtobufCFieldDescriptor test1__field_descriptors[] =
{
  {
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Test1, f1),
    NULL,
    &protobuf_c_empty_string,
    0             /* flags */
  },
  {
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Test1, f2),
    NULL,
    &protobuf_c_empty_string,
    0             /* flags */
  },
  {
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Test1, f3),
    NULL,
    &protobuf_c_empty_string,
    0             /* flags */
  },
  {
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Test1, f4),
    NULL,
    &protobuf_c_empty_string,
    0             /* flags */
  },
  {
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Test1, f5),
    NULL,
    &protobuf_c_empty_string,
    0             /* flags */
  },
  {
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Test1, f6),
    NULL,
    NULL,
    0             /* flags */
  },
  {
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Test1, f7),
    NULL,
    NULL,
    0             /* flags */
  },
  {
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Test1, f8),
    NULL,
    &protobuf_c_empty_string,
    0             /* flags */
  },
  {
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Test1, f9),
    NULL,
    &protobuf_c_empty_string,
    0             /* flags */
  },
};
const ProtobufCMessageDescriptor test1__descriptor =
{
  sizeof(Test1),
  sizeof(test1__field_descriptors) / sizeof(ProtobufCFieldDescriptor),
  test1__field_descriptors,
};
